- name: check the connection with virtual machines through ssh protocol
  hosts:
      - management
      - routers
      - ssh_nodes
  strategy: free
  gather_facts: no

  tasks:
  - ping:
    register: result
    until: result is not failed
    retries: 25
    delay: 60

  - name: Get systemd-resolved status (using command)
    command: resolvectl status
    register: resolved_status
    changed_when: false
    check_mode: false
    failed_when: false

  - name: Extract DNS Servers (using regex - handles global and per-link)
    set_fact:
      resolved_upstream_dns: "{{ resolved_status.stdout | regex_findall('DNS Servers: (.*)') | map('trim') | join(' ') | split() }}"
    when: resolved_status.rc == 0

- name: Sandbox networking
  hosts:
  - management
  - routers
  strategy: free
  gather_facts: yes
  become: yes
  become_user: root

  roles:
  - role: interface
    interface_interfaces: '
    {%- import "roles/common/templates/network.j2" as network with context -%}
    {%- set variables = namespace(
      interfaces = [],
      routes = [],
    ) -%}
    {%- if interfaces is defined and interfaces -%}
      {%- for interface in interfaces -%}
        {%- set variables.routes = [] -%}
        {%- if interface.routes is defined and interface.routes -%}
          {%- for route in interface.routes -%}
            {%- set variables.routes = variables.routes + [{
              "gateway": route.gw,
              "mask": route.mask,
              "network": route.net
            }] -%}
          {%- endfor -%}
        {%- endif -%}
        {%- set variables.interfaces = variables.interfaces + [{
          "interface_default_gateway": interface.def_gw_ip,
          "interface_mac": interface.mac,
          "interface_routes": variables.routes,
          "interface_device": network.mac_to_interface(interface.mac)
        }] -%}
      {%- endfor -%}
    {%- endif -%}
    {%- set inventory_mac_addresses = interfaces | map(attribute="mac") | list -%}
    {%- set the_rest_interfaces = network.common_network.interfaces |
      selectattr("macaddress", "defined") |
      rejectattr("macaddress", "in", inventory_mac_addresses) |
      selectattr("type", "eq", "ether") | list
    -%}
    {%- for interface in the_rest_interfaces -%}
      {%- set variables.interfaces = variables.interfaces + [{
        "interface_mac": interface.macaddress,
        "interface_device": interface.device
      }] -%}
    {%- endfor -%}
    {{ variables.interfaces }}'

  tasks:
  - name: set ip forward
    sysctl:
      name: net.ipv4.ip_forward
      value: '{% if ip_forward %}1{% else %}0{% endif %}'
    when: ip_forward is defined

- name: Sandbox networking for netplan hosts
  hosts: ssh_nodes,!routers
  strategy: free
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
    - name: Skip for non-netplan hosts
      ansible.builtin.meta: end_host
      when: ansible_distribution != 'Ubuntu' and (ansible_distribution != 'Debian' or ansible_distribution_version is not version('12', '>='))

    - name: Get user network interface
      set_fact:
        user_network_interface: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4.address', 'defined') | selectattr('ipv4.address', 'eq', user_network_ip) | map(attribute='device') | first }}"

    - name: Create Netplan configuration file
      copy:
        content: |
          #jinja2: trim_blocks: True, lstrip_blocks: True
          network:
            version: 2
            ethernets:
              {% for interface in ansible_interfaces | reject('equalto', 'lo') | sort %}
              {{ interface }}:
                dhcp4: true
                dhcp4-overrides:
                  route-metric: {{ 100 if interface == user_network_interface else 200 }}
                dhcp6: false
              {% endfor %}
        dest: /etc/netplan/50-cloud-init.yaml
        owner: root
        group: root
        mode: '0600'

    - name: Apply Netplan
      command: netplan apply

- name: Install Chrony on MAN node
  hosts: man
  strategy: free
  gather_facts: no
  become: yes
  become_user: root

  tasks:
    - name: Run apt update
      apt:
        update_cache: yes

    - name: Install Chrony
      apt:
        name: chrony

- name: Install and configure Guacamole daemon on MAN node
  hosts: man
  strategy: free
  gather_facts: no
  become: yes
  roles:
    - guacamole

- name: NAT on MAN node
  hosts: man
  strategy: free
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
  - name: get interface of default gateway
    shell: ip route list | grep ^default | head -n 1
    changed_when: False
    register: default_gateway

  - set_fact:
      default_gateway_interface: '{{ default_gateway.stdout | regex_search("(?<=dev )[^ ]+") }}'
  - set_fact:
      default_gateway_interface_ip: '{{ ansible_facts[default_gateway_interface]["ipv4"]["address"] }}'

  - name: setup NAT
    include_role:
      name: iptables
    vars:
      iptables_rules:
        - table: nat
          chain: POSTROUTING
          out_interface: '{{ default_gateway_interface }}'
          jump: MASQUERADE

  - name: Set man logging forward
    include_role:
      name: man-logging-forward
    vars:
      kmlf_destination: "{{ global_head_ip }}"

- name: Setup DROP rules on MAN
  hosts: man
  strategy: free
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
    - set_fact:
        private_ip_address_range: ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16', '224.0.0.0/4']
    - set_fact:
        host_interface: 'ens5'

    - name: setup
      include_role:
        name: iptables
      vars:
        iptables_rules:
          - chain: FORWARD
            destination: '{{ item }}'
            in_interface: '{{ host_interface }}'
            out_interface: '{{ hostvars["man"]["default_gateway_interface"] }}'
            jump: DROP
      loop: '{{ private_ip_address_range }}'

- name: Test sandbox networking
  hosts:
  - management
  - routers
  - ssh_nodes
  strategy: free
  become: yes
  become_user: root

  tasks:
  - command: 'ping -c 3 {{ hostvars["man"]["default_gateway_interface_ip"] }}'
    changed_when: False
    register: ping_result
    until: ping_result is not failed
    retries: 18
    delay: 10

- name: User access on MAN and UAN
  hosts:
  - man
  - uan
  strategy: free
  gather_facts: no
  become: yes
  become_user: root

  roles:
    - role: user-access
      user_access_username: user
      user_access_ssh_public_key_options: 'restrict,port-forwarding,command="/usr/sbin/nologin"'

- name: User and management access on Proxy Jump
  hosts:
  - proxy-jump
  strategy: free
  gather_facts: no
  become: yes
  become_user: root

  pre_tasks:
    - name: check existence of other users from pool
      find:
        file_type: directory
        paths: /home
        patterns: '{{ user_access_mgmt_name }}*'
      register: other_users_from_pool

    - set_fact:
        other_users_from_pool_exists: '{{ other_users_from_pool.files | map(attribute="pw_name") | reject("eq", user_access_mgmt_name) | reject("eq", user_access_user_name) | list | length > 0 }}'
        user_access_present: '{{ user_access_present | default(True) }}'


  roles:
    - role: user-access
      user_access_username: '{{ user_access_user_name }}'
      user_access_ssh_public_key: '{{ global_ssh_public_user_key }}'
      user_access_ssh_public_key_options: 'restrict,port-forwarding,command="/usr/sbin/nologin"'
      when: user_access_present

    - role: user-access
      user_access_username: '{{ user_access_mgmt_name }}'
      user_access_ssh_public_key: '{{ global_ssh_public_mgmt_key }}'
      user_access_ssh_public_key_options: 'restrict,port-forwarding,command="/usr/sbin/nologin"'
      when: user_access_present

  tasks:
    - name: remove sandbox user from Proxy Jump
      user:
          name: '{{ user_access_user_name }}'
          state: absent
          remove: yes
          force: yes
      when: not user_access_present

    - name: remove pool mgmt user from Proxy Jump
      user:
          name: '{{ user_access_mgmt_name }}'
          state: absent
          remove: yes
          force: yes
      when: not user_access_present and not other_users_from_pool_exists

- name: Configure user access for user accessible hosts
  hosts: user_accessible_nodes:&ssh_nodes
  strategy: free
  gather_facts: true
  become: true
  become_user: root

  roles:
    - role: user-access
      user_access_username: user
      user_access_password: Password123
      user_access_sudo: True

- name: check the connection with virtual machines through winrm protocol
  hosts: winrm_nodes
#  strategy: free
  gather_facts: no

  tasks:
  - name: Wait 1600 seconds for target connection to become reachable/usable
    wait_for_connection:
      connect_timeout: 10
      timeout: 1600

  - name: test sandbox networking
    win_command: 'ping {{ hostvars["man"]["default_gateway_interface_ip"] }}'

  - name: ensure existence of SSH directory
    win_file:
      path: 'C:\Users\{{ ansible_user }}\.ssh'
      state: directory

  - name: add public key to authorized keys
    win_copy:
      dest: 'C:\Users\{{ ansible_user }}\.ssh\authorized_keys'
      content: '{{ lookup("file", global_ssh_public_mgmt_key) }}'

- name: Configure user access for user accessible windows hosts
  hosts: user_accessible_nodes:&winrm_nodes
  gather_facts: yes

  roles:
    - role: user-access-windows
      user_access_username: user
      user_access_password: Password123
      user_access_admin: True

- name: remove stack name prefix from hostnames of ssh nodes
  hosts:
      - management
      - ssh_nodes
  strategy: free
  gather_facts: no
  become: yes

  tasks:
      - name: set a new hostname
        hostname:
            name: '{{ inventory_hostname }}'

      - name: Make cloud-init to preserve changes
        lineinfile:
          path: /etc/cloud/cloud.cfg
          regexp: '^manage_etc_hosts'
          line: 'manage_etc_hosts: localhost'
        when: ansible_facts['os_family'] != 'FreeBSD'

      - name: Make cloud-init to preserve changes
        lineinfile:
          path: /usr/local/etc/cloud/cloud.cfg
          regexp: '^manage_etc_hosts'
          line: 'manage_etc_hosts: localhost'
        when: ansible_facts['os_family'] == 'FreeBSD'

      - name: remove stack name prefix from /etc/hosts file
        replace:
            path: /etc/hosts
            regexp: '{{ global_sandbox_name }}-'
            replace: ''

- name: remove stack name prefix from hostnames of winrm nodes
  hosts:
      - winrm_nodes
  strategy: free
  gather_facts: no

  tasks:
      - name: set a new hostname
        win_hostname:
            name: '{{ inventory_hostname }}'
        register: win_hostname_return_value

      - name: reboot machine
        win_reboot:
        when: win_hostname_return_value.reboot_required

- name: Prepare docker enabled machines
  hosts:
    - docker_hosts
  become: yes

  roles:
    - role: user-access
      user_access_username: crczp-user
      user_access_ssh_public_key_options: 'restrict,port-forwarding,command="/usr/sbin/nologin"'

  tasks:
    - name: Install required system packages for Docker
      apt:
        name: gnupg-agent
        state: latest
        update_cache: yes

    - name: Install docker-compose
      include_role:
        name: docker-compose

    - name: Add administrator to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Copy user public key to remote machine
      copy:
        src: "{{ global_ssh_public_user_key }}"
        dest: "/home/crczp-user/.ssh/user_rsa.pub"

    - name: Copy docker container directory to remote machine
      copy:
        src: "{{ containers_path }}"
        dest: "/home/crczp-user/containers"

    - name: Build docker containers
      community.docker.docker_compose_v2:
        project_src: "/home/crczp-user/containers/"

- name: Deploy blackbox-exporter & prometheus on man
  hosts:
   - man
  become: yes
  roles:
    - role: prometheus
      when: (groups["monitor-os"] is defined) or (groups["monitor-icmp"] is defined) or
        (groups['monitored_hosts'] is defined and (groups['monitored_hosts']|length>0))
    - role: blackbox-exporter
      when: (groups["monitor-os"] is defined) or (groups["monitor-icmp"] is defined) or
        (groups['monitored_hosts'] is defined and (groups['monitored_hosts']|length>0))

- name: Deploy node-exporter on listed Linux hosts
  hosts: monitor-os,!winrm_nodes
  become: yes
  roles:
    - role: node-exporter
      when:
        - ansible_os_family == 'Debian' or ansible_os_family == 'RedHat' or ansible_os_family == 'FreeBSD'
        - groups["monitor-os"] is defined and (groups["monitor-os"]|length>0)

- name: Deploy node-exporter on all Linux hosts
  hosts: routers,hosts,!proxy-jump,!winrm_nodes
  become: yes
  roles:
    - role: node-exporter
      when:
        - ansible_os_family == 'Debian' or ansible_os_family == 'RedHat' or ansible_os_family == 'FreeBSD'
        - groups["monitor-os"] is defined and (groups["monitor-os"]|length == 0)

- name: Deploy windows-exporter on listed Windows hosts
  hosts: monitor-os
  roles:
    - role: windows-exporter
      when:
        - ansible_os_family == "Windows"
        - groups["monitor-os"] is defined and (groups["monitor-os"]|length>0)

- name: Deploy windows-exporter on all Windows hosts
  hosts: hosts,!proxy-jump
  roles:
    - role: windows-exporter
      when:
        - ansible_os_family == "Windows"
        - groups["monitor-os"] is defined and (groups["monitor-os"]|length == 0)
